postgres-db {
    eventlog {
        host = "localhost",
        port = 5432,
        user = "dcb",
        password = "dcb",
        database = "eventlog",
        max = 10
    },
    views {
        host = "localhost",
        port = 5432,
        user = "dcb",
        password = "dcb",
        database = "views",
        max = 10
    }
}