db {
    event-log {
        host = "localhost"
        port = 5445
        user = "dcb"
        password = "dcb"
        database = "eventlog"
        max = 10
    }
    views {
        host = "localhost"
        port = 5445
        user = "dcb"
        password = "dcb"
        database = "views"
        max = 10
    }
}